# Generated by Django 4.2.3 on 2023-07-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('tel', models.IntegerField()),
                ('isBanned', models.BooleanField()),
                ('compte_type', models.CharField(editable=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='usertest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=' ', max_length=50)),
                ('password', models.TextField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.person')),
                ('numb_card_national', models.IntegerField()),
                ('wilaya', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0, editable=False, max_length=1)),
                ('category_of_worker', models.CharField(default=' ', max_length=10)),
            ],
            bases=('api.person',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.person')),
                ('wilaya', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
            ],
            bases=('api.person',),
        ),
    ]
