# Generated by Django 4.2.3 on 2023-07-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_artisan_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='category_of_worker',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='compte_type',
            field=models.CharField(choices=[('client', 'Client'), ('worker', 'Worker')], default='client', max_length=10),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='numb_card_national',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='rating',
            field=models.FloatField(default=0, editable=False, max_length=1),
        ),
    ]
