# Generated by Django 4.2.3 on 2023-07-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_artisan_category_of_worker_user_compte_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='compte_type',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
