# Generated by Django 4.2.3 on 2023-07-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_compte_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='compte_type',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
